# Generated by Django 4.2.4 on 2023-10-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_checkout_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_price',
            field=models.IntegerField(default='120'),
        ),
    ]
