# Generated by Django 4.2.7 on 2024-03-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_onlinepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('img', models.ImageField(upload_to='static\\images')),
            ],
        ),
    ]
