# Generated by Django 4.2.7 on 2024-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_productform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
