# Generated by Django 4.2.7 on 2024-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productform',
            name='district',
            field=models.CharField(default='xyz', max_length=20),
        ),
    ]
