# Generated by Django 4.2.7 on 2024-04-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_cart_products_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productform',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
    ]
